Sign UP API
cristian0x/GigaCal pull request #4
Opened 2023-11-27 16:56 UTC by bartekbaran

2023-11-28 10:50 UTC, klukaasik reviewed
Komentarze w review

2023-11-28 10:50 UTC, klukaasik commented on src/main/java/com/gigacal/config/ApplicationAuditAware.java
> +    @Override
Osobiście bym tu linijkę odstępu dał

2023-11-28 10:50 UTC, klukaasik commented on src/main/java/com/gigacal/auth/JwtAuthenticationFilter.java
> +import org.slf4j.Logger;
Niewykorzystywane importy Logger i LoggerFactory

2023-11-28 10:50 UTC, klukaasik commented on src/main/java/com/gigacal/dto/AuthenticationResponseDTO.java
> +import lombok.AllArgsConstructor;
Niewykorzystywany import

2023-11-28 10:50 UTC, klukaasik commented on src/main/java/com/gigacal/entity/UserEntity.java
> +import jakarta.validation.constraints.Min;
Niewykorzystywany import

2023-11-28 10:50 UTC, klukaasik commented on src/main/java/com/gigacal/service/impl/TokenServiceImpl.java
> +
2 niepotrzebne linijki 🤓🤓

2023-11-30 12:52 UTC, agunia2000 requested changes

2023-11-30 12:52 UTC, agunia2000 commented on src/main/java/com/gigacal/entity/UserEntity.java
>  ;
zbędny średnik w drugiej linii

2023-11-30 12:52 UTC, agunia2000 commented on src/main/java/com/gigacal/entity/CalendarEntity.java
> +    @Column(name = "calendar_id")
te prefiksy przy kolumnach id muszą być? calendar_id bardziej pasuje jako foreign key w innych tabelach natomiast w tabeli calendars powinno być samo id (według mnie jest to bardziej czytelne)

2023-11-30 12:52 UTC, agunia2000 commented on src/main/java/com/gigacal/service/impl/LogoutServiceImpl.java
> +
zdublowana pusta linia

2023-11-30 17:24 UTC, klukaasik approved these changes
You can merge

2023-11-30 17:25 UTC, agunia2000 approved these changes

2023-11-30 17:25 UTC, merged